# nix integration
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# set zsh highlighting theme
source ~/.config/home-manager/programs/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh

# set JAVA_HOME using asdf
. ~/.asdf/plugins/java/set-java-home.zsh

export TESTCONTAINERS_RYUK_DISABLED=true
export DOCKER_HOST=unix:///Users/ainharan/.colima/docker.sock

# add opencode to $PATH
export PATH=/Users/ainharan/.opencode/bin:$PATH


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

path+=('/Users/ainharan/.local/bin')
export path

# Enable colors for ls
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
alias ls='ls -G'
